server:
  port: ${custom.port}
spring:
  application:
    name: member-service
eureka:
  client:
    service-url:
      defaultZone: ${custom.eureka-server}
mybatis:
  configuration:
    map-underscore-to-camel-case: true